version: "3.9"
services:
  client:
    image: whiteboard/client
    build: ./client/source
    ports:
      - 3000:80
    depends_on:
      - server

  server:
    image: whiteboard/server
    build: ./server/source
    ports:
      - 5000:80